"use client"

export const pillarOneIndicators = [
  {
    id: "1.1.1",
    shortName: "Innovation Strategy Alignment",
    description: "Degree to which innovation strategy aligns with overall business strategy.",
    howToCalculate: "Rate from 0-2 based on documented alignment and integration",
    measurementUnit: "Score (0-2)",
    remark: "Assess formal documentation and strategic integration",
    example: "Fully documented and integrated strategy scores 2",
    evidenceRequired: "Strategic documents showing innovation-business alignment",
    maxScore: 2,
  },
  {
    id: "1.1.2",
    shortName: "Innovation Budget Allocation",
    description: "Percentage of total budget allocated to innovation activities.",
    howToCalculate: "Calculate as (Innovation Budget / Total Budget) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Include R&D, new product development, and process innovation",
    example: "A company with $10M total budget and $1M innovation budget scores 10%",
    evidenceRequired: "Budget documents showing innovation allocation",
    maxScore: 100,
  },
  {
    id: "1.1.3",
    shortName: "Innovation Governance Structure",
    description: "Formal governance structure for innovation decision-making.",
    howToCalculate: "Rate from 0-2 based on formal structure and processes",
    measurementUnit: "Score (0-2)",
    remark: "Assess formal committees, roles, and decision-making processes",
    example: "Dedicated innovation committee with clear processes scores 2",
    evidenceRequired: "Governance documents and organizational charts",
    maxScore: 2,
  },
  {
    id: "1.1.4",
    shortName: "Innovation Performance Metrics",
    description: "Comprehensive metrics system for measuring innovation performance.",
    howToCalculate: "Rate from 0-3 based on metrics comprehensiveness and usage",
    measurementUnit: "Score (0-3)",
    remark: "Include input, process, output, and outcome metrics",
    example: "Complete metrics system with regular reporting scores 3",
    evidenceRequired: "Metrics documentation and performance reports",
    maxScore: 3,
  },
  {
    id: "1.2.1",
    shortName: "CEO Innovation Commitment",
    description: "CEO's personal commitment to innovation leadership.",
    howToCalculate: "Binary: 1 if CEO demonstrates clear innovation leadership, 0 otherwise",
    measurementUnit: "Binary (0-1)",
    remark: "Assess CEO's public statements, actions, and resource allocation",
    example: "CEO actively promotes innovation and allocates resources scores 1",
    evidenceRequired: "CEO statements, speeches, and resource allocation decisions",
    maxScore: 1,
  },
  {
    id: "1.2.2",
    shortName: "Leadership Innovation Training",
    description: "Percentage of leadership team with innovation training.",
    howToCalculate: "Calculate as (Trained Leaders / Total Leaders) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Include formal innovation management training programs",
    example: "8 out of 10 leaders trained in innovation management scores 80%",
    evidenceRequired: "Training records and certificates",
    maxScore: 100,
  },
  {
    id: "1.2.3",
    shortName: "Innovation Culture Assessment",
    description: "Assessment of innovation culture within the organization.",
    howToCalculate: "Calculate as (Positive Responses / Total Responses) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Based on employee surveys and culture assessments",
    example: "75% of employees report positive innovation culture scores 75%",
    evidenceRequired: "Culture assessment reports and survey results",
    maxScore: 100,
  },
  {
    id: "1.2.4",
    shortName: "Innovation Leadership Accountability",
    description: "Formal accountability mechanisms for innovation leadership.",
    howToCalculate: "Rate from 1-5 based on accountability structure and enforcement",
    measurementUnit: "Score (1-5)",
    remark: "Assess formal KPIs, reviews, and consequences",
    example: "Clear KPIs with regular reviews and consequences scores 5",
    evidenceRequired: "Accountability frameworks and review processes",
    maxScore: 5,
  },
  {
    id: "1.3.1",
    shortName: "Innovation Policy Framework",
    description: "Comprehensive innovation policy framework.",
    howToCalculate: "Rate from 0-3 based on policy comprehensiveness and implementation",
    measurementUnit: "Score (0-3)",
    remark: "Include policies for R&D, IP, collaboration, and risk management",
    example: "Complete policy framework with clear implementation scores 3",
    evidenceRequired: "Policy documents and implementation guidelines",
    maxScore: 3,
  },
  {
    id: "1.3.2",
    shortName: "IP Strategy Implementation",
    description: "Percentage of IP strategy recommendations implemented.",
    howToCalculate: "Calculate as (Implemented Recommendations / Total Recommendations) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Based on IP strategy review and implementation tracking",
    example: "15 out of 20 IP recommendations implemented scores 75%",
    evidenceRequired: "IP strategy documents and implementation tracking",
    maxScore: 100,
  },
  {
    id: "1.3.3",
    shortName: "Innovation Risk Management",
    description: "Formal risk management framework for innovation activities.",
    howToCalculate: "Rate from 0-2 based on framework completeness and usage",
    measurementUnit: "Score (0-2)",
    remark: "Assess risk identification, assessment, and mitigation processes",
    example: "Comprehensive risk framework with regular reviews scores 2",
    evidenceRequired: "Risk management frameworks and assessment reports",
    maxScore: 2,
  },
  {
    id: "1.3.4",
    shortName: "Innovation Compliance Rate",
    description: "Percentage of innovation activities compliant with policies.",
    howToCalculate: "Calculate as (Compliant Activities / Total Activities) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Based on compliance audits and monitoring",
    example: "90% of innovation activities comply with policies scores 90%",
    evidenceRequired: "Compliance audit reports and monitoring data",
    maxScore: 100,
  },
  {
    id: "1.4.1",
    shortName: "Strategic Flexibility Index",
    description: "Organization's ability to adapt strategy based on innovation insights.",
    howToCalculate: "Rate from 0-3 based on adaptation frequency and effectiveness",
    measurementUnit: "Score (0-3)",
    remark: "Assess strategic pivots and adaptation mechanisms",
    example: "Regular strategic adaptations based on innovation insights scores 3",
    evidenceRequired: "Strategic adaptation records and decision documentation",
    maxScore: 3,
  },
  {
    id: "1.4.2",
    shortName: "Innovation Feedback Integration",
    description: "Percentage of innovation feedback integrated into strategic decisions.",
    howToCalculate: "Calculate as (Integrated Feedback / Total Feedback) × 100",
    measurementUnit: "Percentage (%)",
    remark: "Based on feedback tracking and integration monitoring",
    example: "80% of innovation feedback influences strategic decisions scores 80%",
    evidenceRequired: "Feedback tracking systems and integration reports",
    maxScore: 100,
  },
  {
    id: "1.4.3",
    shortName: "Innovation Learning Systems",
    description: "Formal systems for capturing and sharing innovation learnings.",
    howToCalculate: "Binary: 1 if formal learning systems exist, 0 otherwise",
    measurementUnit: "Binary (0-1)",
    remark: "Assess knowledge management and learning capture systems",
    example: "Formal systems for capturing and sharing learnings scores 1",
    evidenceRequired: "Learning system documentation and usage reports",
    maxScore: 1,
  },
  {
    id: "1.4.4",
    shortName: "Innovation Performance Review",
    description: "Regular review and adjustment of innovation performance.",
    howToCalculate: "Rate from 0-2 based on review frequency and action effectiveness",
    measurementUnit: "Score (0-2)",
    remark: "Assess review processes and resulting improvements",
    example: "Quarterly reviews with effective improvement actions scores 2",
    evidenceRequired: "Review schedules and improvement action tracking",
    maxScore: 2,
  }
];
